### ISSUE TITLE
168+ typos

### ISSUE THREAD

**Issue by lkalir** [Repkap11/Burger#2]
![brugers](https://user-images.githubusercontent.com/30846115/29095743-005e8fce-7c60-11e7-93d9-2c689caf32f9.png)

Adding this so issue is officially documented.

**Comment by Repkap11** [comment]
Try this:
grep -rl Burger . | xargs sed -i s/Burger/Burgr/g ; grep -rl burger . | xargs sed -i s/burger/burgr/g

**Comment by lkalir** [comment]
![great](https://user-images.githubusercontent.com/30846115/29097435-ca0894d0-7c67-11e7-8c75-fa833b16a7b2.png)

Thanks! That worked!
